# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: jefferyhhh/decap-astro-website
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/c8b938b5-9880-4116-8403-3a4438095ff5/pkce
  auth_token_endpoint: /sites/c8b938b5-9880-4116-8403-3a4438095ff5/token
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Logo for Decap login page. Change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site link in DecapCMS (optional)
site_url: https://decap-astro-website.netlify.app/

media_folder: src/assets/images/blog # Location where files will be stored in the repo - we store them in src so that Astro can optimize them.
public_folder: "@assets/images/blog" # Same folder as above, but using a path alias for easier referencing in the markdown files.

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
    label: "Blog" # Used in the admin dashboard UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - {
          label: "Is it a featured post?",
          name: "isFeatured",
          widget: "boolean",
          default: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
